apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: gursukhab/django:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              python manage.py migrate --noinput &&
              gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
          ports:
            - containerPort: 8000
          env:
           - name: DB_NAME                                                                                                             
              value: test_db                                                                                                            
            - name: DB_USER                                                                                                             
              value: root                                                                                                               
            - name: DB_PASSWORD                                                                                                         
              value: root                                                                                                               
            - name: DB_HOST                                                                                                             
              value: db-service                                                                                                         
            - name: DB_PORT                                                                                                             
              value: "3306"                                                                                                             
          readinessProbe:                                                                                                               
            httpGet:                                                                                                                    
              path: /admin                                                                                                              
              port: 8000                                                                                                                
            initialDelaySeconds: 30                                                                                                     
            periodSeconds: 10                                                                                                           
            timeoutSeconds: 5                                                                                                           
            successThreshold: 1                                                                                                         
            failureThreshold: 3
