apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: notes-app
type: Opaque
stringData:
  DB_NAME: test_db
  DB_USER: root
  DB_PASSWORD: root
  DB_PORT: "3306"
  DB_HOST: db-service
