apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: notes-app
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32000  # Optional: Kubernetes will assign one if omitted
