apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: notes-app
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31159  # You can change this within the range 30000–32767
